In [1]:
import pandas as pd

raw = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/rawfiles/CARD_SUBWAY_MONTH_201901.csv')
raw.head()

       사용일자  노선명   역ID   역명  승차총승객수  하차총승객수      등록일자
0  20190101  경춘선  1323   가평    1520    1436  20190104
1  20190101  경춘선  1322   상천     275     114  20190104
2  20190101  경춘선  1321   청평    1509    1083  20190104
3  20190101  경춘선  1320  대성리     357     271  20190104
4  20190101  경춘선  1319   마석    1772    1963  20190104

In [2]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18334 entries, 0 to 18333
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    18334 non-null  int64
 1   노선명     18334 non-null  object
 2   역ID     18334 non-null  int64
 3   역명      18334 non-null  object
 4   승차총승객수  18334 non-null  int64
 5   하차총승객수  18334 non-null  int64
 6   등록일자    18334 non-null  int64
dtypes: int64(5), object(2)
memory usage: 1002.8+ KB

## 여러개의 파일 하나로 합치기

In [3]:
raw = pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [4]:
import os

files = os.listdir('/content/drive/My Drive/Colab Notebooks/data/rawfiles')
files

['CARD_SUBWAY_MONTH_201901.csv',
 'CARD_SUBWAY_MONTH_201902.csv',
 'CARD_SUBWAY_MONTH_201903.csv',
 'CARD_SUBWAY_MONTH_201904.csv',
 'CARD_SUBWAY_MONTH_201906.csv',
 'CARD_SUBWAY_MONTH_201905.csv']

In [7]:
# 파일 하나씩 불러와서 한파일로 합치기

for file in files:

  fpath = '/content/drive/My Drive/Colab Notebooks/data/rawfiles/' + file
  # print(fpath)

  temp = pd.read_csv(fpath)
  raw = raw.append(temp, ignore_index=True) #기존 인덱스는 무시하고 병합

In [8]:
raw

           사용일자  노선명   역ID       역명  승차총승객수  하차총승객수      등록일자
0      20190101  경춘선  1323       가평    1520    1436  20190104
1      20190101  경춘선  1322       상천     275     114  20190104
2      20190101  경춘선  1321       청평    1509    1083  20190104
3      20190101  경춘선  1320      대성리     357     271  20190104
4      20190101  경춘선  1319       마석    1772    1963  20190104
...         ...  ...   ...      ...     ...     ...       ...
99337  20190531  수인선  1885       연수    6405    6455  20190603
99338  20190531  수인선  1884      원인재    5465    5571  20190603
99339  20190531  수인선  1883  남동인더스파크    2582    2910  20190603
99340  20190531  8호선  2822       산성    7161    6841  20190603
99341  20190531  중앙선  1220       지평      66      84  20190603

[99342 rows x 7 columns]

In [9]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99342 entries, 0 to 99341
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    99342 non-null  int64
 1   노선명     99342 non-null  object
 2   역ID     99342 non-null  int64
 3   역명      99342 non-null  object
 4   승차총승객수  99342 non-null  int64
 5   하차총승객수  99342 non-null  int64
 6   등록일자    99342 non-null  int64
dtypes: int64(5), object(2)
memory usage: 5.3+ MB

### 요일 추가하기

In [10]:
from datetime import datetime

In [12]:
# 날짜 컬럼을 불러와서, 순서대로 요일을 점검하여 리스트에 저장

weekday_dict = [ '월','화','수','목','금','토','일']
weekday_list = []

for date_str in raw['사용일자']:

  date = datetime.strptime(str(date_str), '%Y%m%d')
  weekday_index = date.weekday()
  weekday = weekday_dict[weekday_index]
  weekday_list.append(weekday)

In [13]:
raw['요일'] = weekday_list

raw.head()

       사용일자  노선명   역ID   역명  승차총승객수  하차총승객수      등록일자 요일
0  20190101  경춘선  1323   가평    1520    1436  20190104  화
1  20190101  경춘선  1322   상천     275     114  20190104  화
2  20190101  경춘선  1321   청평    1509    1083  20190104  화
3  20190101  경춘선  1320  대성리     357     271  20190104  화
4  20190101  경춘선  1319   마석    1772    1963  20190104  화

In [15]:
raw.columns

Index(['사용일자', '노선명', '역ID', '역명', '승차총승객수', '하차총승객수', '등록일자', '요일'], dtype='object')

In [17]:
# 요일을 사용일자 다음에 나오도록 컬럼 순서를 변경하겠습니다. 

raw = raw[['사용일자', '요일', '노선명', '역ID', '역명', '승차총승객수', '하차총승객수', '등록일자']]

# 데이터 저장하기

In [18]:
raw.to_excel('/content/drive/My Drive/Colab Notebooks/data/subway_raw.xlsx', index = False)